README.md, src/main/scala/com/typesafe/sbt/SbtGit.scala, src/main/scala/com/typesafe/sbt/git/JGit.scala, src/main/scala/com/typesafe/sbt/git/ReadableGit.scala
Git has built in very nice way of versioning as described here: http://git-scm.com/docs/git-describe
This PR adds support to getting version from git describe command. It requires setting `git.useGitDescribe := true`, otherwise behaves as before.
=> Git describe versioning

src/main/scala/com/typesafe/sbt/SbtGit.scala
Now we get a single output prefixed with sbt log level, thus fixing issue #34. For example:
```
> git status
[info] On branch master
[info] Untracked files:
[info]   (use "git add <file>..." to include in what will be committed)
[info]
[info] 	project/project/
[info] 	project/target/
[info] 	target/
[info]
[info] nothing added to commit but untracked files present (use "git add" to track)
```
or 
```
> git log --oneline
[info] 2dc5048 Commiting it
[info] b517834 Commenting that line
[info] fb6e1df Initial commit
```
=> Removing unnecessary println since we already pass a logger to GitRunner

src/main/scala/com/typesafe/sbt/SbtGit.scala, src/main/scala/com/typesafe/sbt/git/JGit.scala, src/main/scala/com/typesafe/sbt/git/ReadableGit.scala
Detects uncommitted changes and appends a signifier at the end of the version.
for example:
```
> show version
[info] 58308ce755ede57f19e78acb24bbab1c1ecfc691-SNAPSHOT
```
It exposes another key associated with version number, that defaults to Some("SNAPSHOT"):
```
val uncommittedSignifier = SettingKey[Option[String]]("uncommitted-signifier", "Optional additional signifier to signify uncommitted changes")
```
The actual signifier is optional and can be overridden:
```
> set git.uncommittedSignifier := Some("UNCOMMITTED")
> show version
[info] 58308ce755ede57f19e78acb24bbab1c1ecfc691-UNCOMMITTED
```
or even left empty:
```
> set git.uncommittedSignifier := None
> show version
[info] 58308ce755ede57f19e78acb24bbab1c1ecfc691
```
It uses JGit's status command to detect uncommitted changes …
=> Adding an additional signifier if there are uncommitted changes

README.md, src/main/scala/com/typesafe/sbt/SbtGit.scala, src/sbt-test/git-versioning/find-environment-variable/build.sbt, src/sbt-test/git-versioning/find-tag-newest/changes/build.sbt, src/sbt-test/git-versioning/find-tag/changes/build.sbt, src/sbt-test/git-versioning/no-base-version/changes/build.sbt, src/sbt-test/git-versioning/uncommitted-signifier/changes/build.sbt, src/sbt-test/git-versioning/uncommitted-signifier/project/plugins.sbt, src/sbt-test/git-versioning/uncommitted-signifier/test, src/sbt-test/git-versioning/use-describe/changes/build.sbt, src/sbt-test/git-versioning/with-base-version/changes/build.sbt
Review by @eed3si9n.
The idea here is any dependent plugin (like ghpages) can still find the keys in the current path, thus remaining half-ass binary compatible.  I do plan to do a ghpages release shortly after 0.8 is out.
=> Migrate to AutoPlugins in 0.8

src/main/scala/com/typesafe/sbt/SbtGit.scala
The git command parser would not allow quoted strings and that broke the 'git commit' command from sbt console (see issue #77). So I added the possibility to parse quoted strings too.
@hedefalk, I am missing other cases where the parser might fail for a git command?
I'd like to add some tests for the parser too so that this does not happen again in the future, but I'll do that  later.
=> Fixing the git commit command

src/main/scala/com/typesafe/sbt/SbtGit.scala
To be consistent, we should happen the uncommitted signifier, e.g. "-SNAPSHOT",  to tagged version too if there are uncommitted changes in the working directory.
I am not a user of the git describe mechanism, but should we do the same for the git describe version ?
For issue #82
=> Appending uncommitted signifier to tag version too.

src/main/scala/com/typesafe/sbt/git/JGit.scala
Using a brand new instance of JGit for every access should get rid of the ConcurrentModificationException, at the -obvious- cost of creating a new instance of JGit every time, including when fetching the completion options for the git command.
I believe the exceptions are due to thread-unsafe initialisation in JGit combined with sbt trying to initialise independent settings in parallel (the second part is really just a guess).
for issue #85
=> Avoid JGit throwing ConcurrentModificationException

src/main/scala/com/typesafe/sbt/SbtGit.scala, src/sbt-test/git-versioning/uncommitted-signifier/changes/build.sbt, src/sbt-test/git-versioning/uncommitted-signifier/test
Added tests for uncommitted signifier.
And because the tests first broke, I added another condition that sets isSnapshot to true (namely if the working directory has uncommitted changes).
=> Adding test for uncommitted signifier

src/main/scala/com/typesafe/sbt/git/ConsoleGitRunner.scala, src/main/scala/com/typesafe/sbt/git/JGitRunner.scala
for #101 as suggested by @pfn
Concretely a simple mistake like this: 
```
> git tatus
[error] git: 'tatus' is not a git command. See 'git --help'.
[error]
[error] Did you mean this?
[error]     status
java.lang.RuntimeException: Nonzero exit code (1) running git.
at scala.sys.package$.error(package.scala:27)
at scala.Predef$.error(Predef.scala:142)
at com.typesafe.sbt.git.ConsoleGitRunner$.apply(ConsoleGitRunner.scala:30)
at com.typesafe.sbt.SbtGit$GitCommand$$anonfun$1.apply(SbtGit.scala:49)
at com.typesafe.sbt.SbtGit$GitCommand$$anonfun$1.apply(SbtGit.scala:45)
at com.typesafe.sbt.SbtGit$GitCommand$$anonfun$3.apply(SbtGit.scala:56)
at com.typesafe.sbt.SbtGit$GitCommand$$anonfun$3.apply(SbtGit.scala:54)
at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
at …
```
=> No more dumping of the stack when the git command fails.

src/main/scala/com/typesafe/sbt/SbtGit.scala, src/main/scala/com/typesafe/sbt/git/JGit.scala, src/main/scala/com/typesafe/sbt/git/ReadableGit.scala
This PR adds the ability to read the date of the current HEAD commit.
As the return value I've chosen an ISO formatted string of the datetime instead of returning a `java.util.Date`. This is because `Date` is gross and the reliance on an old Java version does not allow using `java.time.OffsetDateTime`.
=> Add headCommitDate

.travis.yml, README.md, build.sbt
I had to exclude a few dependencies explicitly otherwise we'd get resolve errors from sbt (which frankly I don't understand).
=> updating to jgit 4

project/bintray.scala
```
sbt-git/project/bintray.scala:23: val keyword in for comprehension is deprecated
[warn]         val cred = c.asInstanceOf[sbt.DirectCredentials]
[warn]                  ^
[warn] one warning found
```
=> fix warning. remove `val` in for comprehension

src/main/scala/com/typesafe/sbt/SbtGit.scala
Uses Git to automatically initialize scmInfo field with a default value so no special configuration is needed to deploy to Sonatype. #113
=> Default value for scmInfo

build.sbt, project/build.properties, project/plugins.sbt
I have removed the transitive dependency on Log4j 1 introduced by jGit in order to allow users to use their favorite logging library, e.g. Log4j 2 or Logback.
=> Upgrade sbt, remove transitive dep on Log4j

.travis.yml, README.md, build.sbt, project/plugins.sbt
This PR introduces `org.eclipse.jgit`as the main artifact for use in this plugin.
I cannot find any information on what `org.eclipse.jgit.pgm` is but it includes a large amount of unnecessary dependencies like the servlet API, jetty and other things that this plugin definitely doesn't need.
=> Use correct jgit artifact

.travis.yml, README.md, build.sbt, project/build.properties, project/plugins.sbt, src/main/scala/com/typesafe/sbt/git/JGitRunner.scala, test-project/project/build.properties
I wanted to upgrade the version of JGit, so that we can begin to make use of new features.
In order to do so, as noted in existing PR #121 (which I believe is superseded by this PR), we need to bump the version of the JDK, since JGit no longer supports Java 7.
While I was at it, it seemed like a good opportunity to bump the 1.0.x track of SBT to be `1.0.3` instead of a release candidate.
Could I have a review of this, please?
=> Upgrade JGit and SBT 1.0.x

README.md, build.sbt, src/main/scala/com/typesafe/sbt/SbtGit.scala
Currently, when there are multiple version tags on the current commit, one is picked semi-randomly. I say `semi` because it's actually deterministic, but it doesn't quite make sense. Anyway, if there are two tags, it typically picks the highest one, unless the last segment has more decimals (e.g. it picks `0.9` over `0.10`, and `0.99` over `0.100`).
```
git tag v0.1
git tag v0.2
sbt 'show version' #0.2
git tag v0.9
git tag v0.10
sbt 'show version' #0.9
```
Technically you could say "who cares, it's the same commit anyway", but if you then publish the package to the jar repository, you have to pick the right one, and that's the one with the higher version - because the latter one is likely already published and it will fail on the attempt to re-publish.
Note: the [sort …
=> Pick the higher version if there are multiple on the current commit

.travis.yml
https://github.com/travis-ci/travis-ci/issues/10290#issuecomment-432331802
> oraclejdk8 is not preinstalled on Xenial anymore, and cannot be retrieved from Oracle itself anymore. We'd suggest using either openjdk, or the currently supported Oracle JDK.
=> use openjdk instead of oraclejdk

src/main/scala/com/typesafe/sbt/SbtGit.scala
This fixes an edge case where there's multiple tags, and some staged
changes which lead to one of them being a -SNAPSHOT which makes sorting
fail.
=> sort before appending the suffix

README.md, build.sbt, src/sbt-test/git-versioning/find-environment-variable/project/plugins.sbt, src/sbt-test/git-versioning/find-tag-newest/project/plugins.sbt, src/sbt-test/git-versioning/find-tag/project/plugins.sbt, src/sbt-test/git-versioning/get-message/project/plugins.sbt, src/sbt-test/git-versioning/multi-module-project/project/plugins.sbt, src/sbt-test/git-versioning/no-base-version/project/plugins.sbt, src/sbt-test/git-versioning/uncommitted-signifier/project/plugins.sbt, src/sbt-test/git-versioning/use-describe-with-matching/project/plugins.sbt, src/sbt-test/git-versioning/use-describe/project/plugins.sbt, src/sbt-test/git-versioning/with-base-version/project/plugins.sbt
Fixes #198
I think it could be that after merging this pull request we already see a snapshot here: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/sbt/
=> Switch to com.github.sbt

.scala-steward.conf
Since that requires Java 11 and we're not ready to make that requirement.
Replaces #212
=> Configure scala-steward not to update to JGit 6

src/main/scala/com/github/sbt/git/ConsoleGitReadableOnly.scala, src/main/scala/com/github/sbt/git/ConsoleGitRunner.scala, src/main/scala/com/github/sbt/git/GitPlugin.scala, src/main/scala/com/github/sbt/git/GitRunner.scala, src/main/scala/com/github/sbt/git/JGit.scala, src/main/scala/com/github/sbt/git/JGitRunner.scala, src/main/scala/com/github/sbt/git/NullLogger.scala, src/main/scala/com/github/sbt/git/ReadableGit.scala, src/test/scala/com/github/sbt/git/SbtGitSuite.scala
Revives https://github.com/sbt/sbt-git/pull/217, just so there is at least one path forward.
https://github.com/sbt/sbt-git/issues/216 discusses some ideas to publish a transitional artifact under the old group id, but I don't how hard that would be and/or who can do that, since this repo is now setup for CI release on the new group id.
https://github.com/sbt/sbt-git/pull/217 notes that if the old/new version of the plugin end up on the same build, the build will break. But that's not the end of the world: it's no different than a fatal eviction error due to a version incompatibility. In any case, it's better than non-determinate behavior if the package was kept the same.
IMO if it's possible to keep publishing to the old group id, instead of trying to do a transitional-artifact-hack the …
=> Change package to `com.github.sbt.git`

src/main/scala/com/github/sbt/git/ConsoleGitReadableOnly.scala, src/main/scala/com/github/sbt/git/ConsoleGitRunner.scala, src/main/scala/com/github/sbt/git/GitPlugin.scala
Three issues! First, loads of commands can crash under certain circumstances, such as when cloned without tags. Wrapping everything in `Try` should fix this. Second, grepping `git status` is very much the wrong way to look for uncommitted changes. This is why `git status -s` exists. Third, the logger is *very* chatty, so I made it configurable and dropped the default level to `Debug`.
This is blocking typelevel/cats-effect#2942
=> Fix console reader issues

README.md, src/main/scala/com/github/sbt/git/GitPlugin.scala, src/sbt-test/git-versioning/multi-module-project-use-describe/README2.md
Add `useReadableConsoleGit` to autoImport.
Update documentation to explain the default of dual-use JGit and
executable, and how to customize if either one is undesirable.
=> Publicize option to disable JGit

src/main/scala/com/github/sbt/git/ConsoleGitReadableOnly.scala
In monorepos (in this example [guardrail](https://github.com/guardrail-dev/guardrail)), the same ref will occasionally have multiple tags.
Relying on `git describe` without `--match` could resolve the wrong tag for different modules.
Unfortunately JGit still does not support git worktree (though that seems to be [coming soon](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475)!), so I'm stuck on CLI git.
Thank you
=> Adding a describedVersion(...) for ConsoleGitReadableOnly

src/main/scala/com/github/sbt/git/GitPlugin.scala
While I was profiling the loading time of [softwaremill/sttp](https://github.com/softwaremill/sttp) build, I noticed that `sbt-git` takes about half of the CPU time. Indeed it seems that `git.describedVersion` is quite expensive as it needs to unpack Git object directories. The problem is this operation is repeated too many times: once for each sub-project of the build (~200 projects in the case of sttp).
This PR eliminates the redundant calls to `describedVersion`: if the input settings of the `ThisProject` and `ThisBuild` are the same, the project reuses `ThisBuild / gitDescribedVersion` instead of recomputing it.
On [softwaremill/sttp](https://github.com/softwaremill/sttp) it reduces the loading time by 45% (12 seconds instead of 22).
=> Perf: Eliminate redundant call to `git.describedVersion`

src/sbt-test/git-versioning/find-tag/changes/build.sbt, src/sbt-test/git-versioning/multi-module-project/changes/build.sbt
prepare sbt 2.x
- https://github.com/sbt/sbt/pull/7703
=> use new slash syntax in test

.github/workflows/ci.yml, .github/workflows/publish.yml
* Adds a CI matrix
* Adds ability to build sbt 2.x and 1.x with the matrix
* Switches to temurin and the `actions/setup-java@v4` setup.
* Switches to checkout@v4
=> Add build matrix, and build for sbt 2.0

build.sbt, src/main/scala/com/github/sbt/git/GitPlugin.scala, src/main/scala/com/github/sbt/git/JGit.scala, src/main/scala/com/github/sbt/git/ReadableGit.scala
According to https://eed3si9n.com/sbt-2.0.0-M3 the M2 and M3 are not binary compatible, so we need a new sbt-git release.
=> Update sbt 2 up to 2.0.0-M3

build.sbt
snapshots are not correctly versioned: https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/com/github/sbt/sbt-git_2.12_1.0/
=> Remove `GitVersioning` plugin, we use sbt-ci-release + dynver
